package identifiers;

public enum AnnotatedExpressionType
{
    ANNOTATED_ASSIGNMENT_EXPRESSION,
    ANNOTATED_BINARY_EXPRESSION,
    ANNOTATED_LITERAL_EXPRESSION,
    ANNOTATED_UNARY_EXPRESSION,
    ANNOTATED_VARIABLE_EXPRESSION
}
