package identifiers;

public enum AnnotatedStatementType
{
    ANNOTATED_SOURCE_STATEMENT,
    ANNOTATED_EXPRESSION_STATEMENT,
    ANNOTATED_BLOCK_STATEMENT,
    ANNOTATED_CONDITIONAL_STATEMENT,
    ANNOTATED_LOOP_STATEMENT
}
