package identifiers;

public enum ExpressionType
{
    ASSIGNMENT_EXPRESSION,
    BINARY_EXPRESSION,
    IDENTIFIER_EXPRESSION,
    LITERAL_EXPRESSION,
    PARENTHESIZED_EXPRESSION,
    UNARY_EXPRESSION
}
