package identifiers;

public enum ExpressionType
{
    ASSIGNMENT_EXPRESSION_TOKEN,
    BINARY_EXPRESSION_TOKEN,
    LITERAL_EXPRESSION_TOKEN,
    IDENTIFIER_EXPRESSION_TOKEN,
    PARENTHESIZED_EXPRESSION_TOKEN,
    UNARY_EXPRESSION_TOKEN
}
