package identifiers;

public enum OperatorType
{
    // Binary Operators
    ADDITION_OPERATOR,
    SUBTRACTION_OPERATOR,
    MULTIPLICATION_OPERATOR,
    DIVISION_OPERATOR,
    POWER_OPERATOR,
    MODULO_OPERATOR,
    AND_OPERATOR,
    OR_OPERATOR,
    EQUALS_EQUALS_OPERATOR,
    NOT_EQUALS_OPERATOR,
    GREATER_OPERATOR,
    LESS_OPERATOR,
    GREATER_EQUALS_OPERATOR,
    LESS_EQUALS_OPERATOR,

    // Unary Operators
    IDENTITY_OPERATOR,
    NEGATION_OPERATOR,
    LOGIC_NEGATION_OPERATOR,
}
