package identifiers;

public enum TokenType
{
    // Primary Tokens
    NUMBER_TOKEN,
    STRING_TOKEN,
    IDENTIFIER_KEYWORD_TOKEN,
    WHITE_SPACE_TOKEN,

    // Keywords
    TRUE_KEYWORD_TOKEN,
    FALSE_KEYWORD_TOKEN,
    AND_TOKEN,
    OR_TOKEN,

    // Separator Tokens
    OPEN_PARENTHESIS_TOKEN,
    CLOSE_PARENTHESIS_TOKEN,

    // Operator Tokens
    PLUS_TOKEN,
    MINUS_TOKEN,
    STAR_TOKEN,
    SLASH_TOKEN,
    CARET_TOKEN,
    PERCENT_TOKEN,
    GREATER_TOKEN,
    LESS_TOKEN,
    GREATER_EQUALS_TOKEN,
    LESS_EQUALS_TOKEN,
    NOT_TOKEN,
    EQUALS_TOKEN,
    EQUALS_EQUALS_TOKEN,
    NOT_EQUALS_TOKEN,

    // Break Tokens
    BAD_TOKEN,
    EOF_TOKEN
}
