package identifiers;

public enum TokenType
{
    // Primary Tokens
    NUMBER_TOKEN,
    WHITE_SPACE_TOKEN,

    // Operator Tokens
    PLUS_TOKEN,
    MINUS_TOKEN,
    STAR_TOKEN,
    SLASH_TOKEN,
    OPEN_PARENTHESIS_TOKEN,
    CLOSE_PARENTHESIS_TOKEN,
    NOT_TOKEN,
    AND_TOKEN,
    OR_TOKEN,
    EQUALS_EQUALS_TOKEN,
    NOT_EQUALS_TOKEN,
    GREATER_TOKEN,
    LESS_TOKEN,
    GREATER_EQUALS_TOKEN,
    LESS_EQUALS_TOKEN,

    // Keywords
    FALSE_KEYWORD_TOKEN,
    TRUE_KEYWORD_TOKEN,
    IDENTIFIER_KEYWORD_TOKEN,

    // Expression Tokens
    LITERAL_EXPRESSION_TOKEN,
    UNARY_EXPRESSION_TOKEN,
    BINARY_EXPRESSION_TOKEN,
    PARENTHESIZED_EXPRESSION_TOKEN,

    // Break Tokens
    BAD_TOKEN,
    EOF_TOKEN
}
