package types;

public enum AnnotatedExpressionType
{
    ANNOTATED_LITERAL_EXPRESSION,
    ANNOTATED_UNARY_EXPRESSION,
    ANNOTATED_BINARY_EXPRESSION,
    ANNOTATED_IDENTIFIER_EXPRESSION,
    ANNOTATED_ASSIGNMENT_EXPRESSION
}
