package compilation.analysis.syntax;

import compilation.analysis.lexical.Token;
import util.ANSI;

import java.util.List;

/**
 * The ParseTree class is used to hold the root Statement generated by the Parser.
 * <p>
 * When the Parser creates a series of Statement objects, the root Statement is held here in the form of
 * a ParseTree. Typically, this will be SourceStatement object, but any child of the Statement interface is valid.
 *
 * @author Louis Lefevre
 * @version 1.0
 * @since 1.0
 */
public final class ParseTree
{
    private final Statement statement;
    private static Statement staticStatement;

    /**
     * Constructs a ParseTree object for storing a Statement object.
     * <p>
     * A static copy of the Statement is also saved on initialisation, so that it can be printed later on.
     *
     * @param statement The Statement object to be stored
     */
    public ParseTree(Statement statement)
    {
        this.statement = statement;
        staticStatement = statement;
    }

    public Statement getStatement()
    {
        return statement;
    }

    public static void print()
    {
        printParseTree(staticStatement, "", true);
    }

    private static void printParseTree(Object node, String indent, boolean isLast)
    {
        String marker = ANSI.GREY;
        marker += isLast ? "└──" : "├──";

        if (node instanceof Statement)
            System.out.print(indent + marker + ANSI.CYAN + ((Statement) node).getStatementType());
        else if (node instanceof Expression)
            System.out.print(indent + marker + ANSI.CYAN + ((Expression) node).getExpressionType());
        else if (node instanceof Token)
            System.out.print(indent + marker + ANSI.BRIGHT_RED + ((Token) node).getType());

        if (node instanceof Token && ((Token) node).getValue() != null)
            System.out.print(ANSI.RED + " (" + ((Token) node).getValue() + ")");

        System.out.println();
        indent += ANSI.GREY;
        indent += isLast ? "   " : "│   ";

        if (node instanceof Statement)
        {
            Object lastChild = null;

            for (Object child : ((Statement) node).getChildren())
                lastChild = child;

            for (Object child : ((Statement) node).getChildren())
                if (child instanceof List)
                    for (Object statement : (List) child)
                        printParseTree(statement, indent, child == lastChild);
                else
                    printParseTree(child, indent, child == lastChild);
        }
        else if (node instanceof Expression)
        {
            Object lastChild = null;
            for (Object child : ((Expression) node).getChildren())
                lastChild = child;

            for (Object child : ((Expression) node).getChildren())
                printParseTree(child, indent, child == lastChild);
        }

        System.out.print(ANSI.RESET);
    }
}
